### ISSUE TITLE
"Non-square pixels" error raised for square pixels

### ISSUE THREAD

**Issue by lpda** [radio-astro-tools/pvextractor#107]
Hi,

First of all, thanks for sharing your nice code with the community.

I have run successfully this example https://nbviewer.org/github/keflavich/pvextractor/blob/master/examples/IRAS05358Slicing.ipynb .

However, when I try to run it with my data, I obtain the following error:

> AssertionError                            Traceback (most recent call last)
> ~/.local/lib/python3.8/site-packages/pvextractor/utils/wcs_utils.py in get_spatial_scale(wcs, assert_square)
     > 19             np.testing.assert_almost_equal(abs(pc[0,0]), abs(pc[1,1]))
> ---> 20             np.testing.assert_almost_equal(abs(scale[0,0]), abs(scale[0,1]))
     > 21         except AssertionError:
> 
> /usr/lib/python3/dist-packages/numpy/testing/_private/utils.py in assert_almost_equal(actual, desired, decimal, err_msg, verbose)
    > 599     if abs(desired - actual) >= 1.5 * 10.0**(-decimal):
> --> 600         raise AssertionError(_build_err_msg())
    > 601 
> 
> AssertionError: 
> Arrays are not almost equal to 7 decimals
 > ACTUAL: 8.245905457097879e-05
 > DESIRED: 8.419853447744303e-05
> 
> During handling of the above exception, another exception occurred:
> 
> ValueError                                Traceback (most recent call last)
> <ipython-input-9-c281f7965c86> in <module>
      > 1 endpoints = [(10,10),(30,30)]
      > 2 xy = Path(endpoints)
> ----> 3 pv = extract_pv_slice(hdu, xy)
> 
> ~/.local/lib/python3.8/site-packages/pvextractor/pvextractor.py in extract_pv_slice(cube, path, wcs, spacing, order, respect_nan)
     > 76 
     > 77     if not isinstance(cube, np.ndarray) or wcs is not None:
> ---> 78         scale = get_spatial_scale(wcs)
     > 79         if isinstance(spacing, u.Quantity):
     > 80             pixel_spacing = (spacing / scale).decompose()
> 
> ~/.local/lib/python3.8/site-packages/pvextractor/utils/wcs_utils.py in get_spatial_scale(wcs, assert_square)
     > 20             np.testing.assert_almost_equal(abs(scale[0,0]), abs(scale[0,1]))
     > 21         except AssertionError:
> ---> 22             raise ValueError("Non-square pixels.  Please resample data.")
     > 23 
     > 24     return abs(scale[0,0]) * u.Unit(wcs.wcs.cunit[0])
> 
> ValueError: Non-square pixels.  Please resample data.

The spatial/celestial WCS information of my data is the following one:

> WCS Keywords
> 
> Number of WCS axes: 2
> CTYPE : 'RA---TAN'  'DEC--TAN'  
> CRVAL : 88.04742083333333  -7.456211111111111  
> CRPIX : 28.15333333333333  21.5  
> PC1_1 PC1_2  : 0.999945534290533  -0.0104368794387836  
> PC2_1 PC2_2  : 0.0104368794387836  0.999945534290533  
> CDELT : -8.3333333333333e-05  8.33333333333333e-05  
> NAXIS : 43  40

That is, CDELT values have the same size (with different sign to account for reflection), and PC values correspond to a rotation matrix, so I understand that my pixels are squares.

Based on this, I understand that there is a bug in the function `get_spatial_scale` in the file `utils/wcs_utils.py`, not?

Thanks for your help shedding light on this issue!

**Comment by keflavich** [comment]
You're likely right; I thing we can use an astropy wcs tool `wcs.proj_plane_pixel_scales` instead of what we're using now.

**Comment by lpda** [comment]
Based on the suggested solution by keflavich , I have created the pull request #110 .

**Comment by kmhess** [comment]
Hi, I have a related issue.  I'm not sure if it will be fixed by the PR, but I think the PR hasn't been merged, right?

I have the following code:
```
slice = PathFromCenter(center=SkyCoord(ra=source['pos_x'], dec=source['pos_y'], unit='deg'),
                       length=opt_view, angle=source['kin_pa']*u.deg, width=1*u.arcsec)
mask = fits.open(filename)
mask_pv = extract_pv_slice(mask[0].data, slice, wcs=WCS(mask[0].header, fix=True, translate_units='shd'))
```
And I get the error:
```
AssertionError: 
Arrays are not almost equal to 7 decimals
 ACTUAL: 0.0016675802169471255
 DESIRED: 0.0016657532823994607
```
The error has me stumped.  I don't know what I'm supposed to reproject to fix this since the WCS and the data come from the same fits files and the actual/desired really are almost equal.  Thanks in advance.
Also `CDELT1` and `CDELT2` in the `mask[0].header` are identical and equal to `1.6666670000E-3`
