### ISSUE TITLE
URL broken in the example use case

### ISSUE THREAD

**Issue by lpda** [radio-astro-tools/pvextractor#108]
In the README file, the following example is provided: http://nbviewer.ipython.org/urls/raw.github.com/keflavich/pvextractor/master/examples/IRAS05358Slicing.ipynb

However, the first line of code refers to an URL which is broken:
> url = 'http://files.figshare.com/1213488/iras05358_12co21.fits'

Fortunately, it is possible to find this file in Internet, but it is not trivial. In particular, it is available at https://figshare.com/articles/dataset/IRAS_05358_3543_Data_Cubes/806315

**Comment by keflavich** [comment]
Thanks!  this is classic link rot; figshare has moved its links around.

Could you submit a pull request with this change?

**Comment by lpda** [comment]
I have just tried to do it. I am not familiar with GitHub way of working (I normally use GitLab), so I hope to have done it well.

For any suggestion of proceeding better, please, let me know.

**Comment by keflavich** [comment]
Fixed by #109
