### ISSUE TITLE
would like to plot sources on top of a PV map

### ISSUE THREAD

**Issue by chukus** [radio-astro-tools/pvextractor#114]
Hi, I used extract_pv_slice to make a PV image and I am using an example from the PV extractor pages to display the image with matplotlib. Looks good.

But then, I want to plot on top a list of sources (I have positions, LSR radial velocities). I am converting their DEC positions into offsets using the initial point of the path I defined to make the PV. 
I used matplotlib scatter like 

ax.scatter(dec_offset,rvlsr,marker='o', s=4, alpha=0.5)

the problem is, all the sources clump in a corner of the figure.
I tried  to use set_xlim and set_ylim, but then , the limits on
the image get garbled.

Thanks in advance

**Comment by keflavich** [comment]
Are you sure you're using the right units?

You might need to use a transform to get the data into the right coordinates.... I'm not entirely sure, but could probably help more if you show a complete example.

**Comment by chukus** [comment]
# just before I wrote this, I noticed that if I write the axis limits,
they are in pixel units

> a1=ax.get_xlim()
> a2=ax.get_ylim()
> print(a1,a2)
> (-0.5, 1099.5) (-0.5, 66.5)

this is the header print
CTYPE : 'OFFSET'  'VRAD'  
CRVAL : 0.0  11160.17929  
CRPIX : 1.0  34.0 
CDELT : 0.002083333333  423.3137732  
NAXIS : 1100  67

so perhaps I just need to convert my star data into pixel units? However
that complicates adding errorbars etc.

Here is the script so far

from astropy import units as u
from astropy.coordinates import Galactic
from pvextractor import Path
from pvextractor import extract_pv_slice
from spectral_cube import SpectralCube
from astropy.coordinates import FK5
from astropy.io import fits
import matplotlib.pyplot as plt
from astropy import wcs
import astropy
from astropy.io import ascii
import numpy as np

#this is a path defining a vertical cut across declination on an image of width=2.4 deg
g = FK5([98.0771989,98.07775522] * u.deg, [3.4367890,5.7280606] * u.deg)
path1=Path(g,width=2.4*u.deg)

#I extract the slice from the cube, it looks correct 
cube=SpectralCube.read('somecube.fits')
slice1=extract_pv_slice(cube,path1,spacing=1)
slice1.writeto('my_PVslice.fits', overwrite=True) 

#took this from the example in the documentation, the image looks OK
#axis is in velocity (m/s) vs offset (degrees) units and the colorbar in temperature (K)
ww=wcs.WCS(mifits[0].header)
ax = plt.subplot(111, projection=ww)
im = ax.imshow(mifits[0].data, interpolation='nearest', aspect='auto',cmap='binary')
cb = plt.colorbar(mappable=im)

#sources list
slist='RMC.csv'
cft = ascii.read(slist,format='csv')

ra=cft['RA']
dec=cft['DEC']
rvlsr=cft['RV_LSR']

#this should in m/s and offset units
dec_offset = dec - 3.4367890
vlsr_ms=rvlsr*1000.0

ptt = ax.scatter(dec_offset,rvlsr,marker='o', s=4, alpha=0.5)

and then all sources are piled up because the image is in pixel units

[Spectral_PV-DIAGRAM2.pdf](https://github.com/radio-astro-tools/pvextractor/files/11579562/Spectral_PV-DIAGRAM2.pdf)

thanks in advance

**Comment by chukus** [comment]
indeed, converting to pixel units makes it right

#pass offset, vlsr as N,2 array
mm=np.column_stack((dec_offset,vlsr_ms))

#convert to pixel units
kk=ww.all_world2pix(mm,0)

#add them to the plot
ptt = ax.scatter(kk[:,0],kk[:,1],marker='o', s=4, alpha=0.5)

[Spectral_PV-DIAGRAM2.pdf](https://github.com/radio-astro-tools/pvextractor/files/11579837/Spectral_PV-DIAGRAM2.pdf)
