### ISSUE TITLE
pb using pvextractor

### ISSUE THREAD

**Issue by didelon** [radio-astro-tools/pvextractor#117]
Hello 
I install pvextractor with pip (pip install pvextractor => Successfully installed pvextractor-0.1)
I didn't succeed to install version 0.3 (not found with pip install 'pvextractor>=0.3')

then using the  example given in https://pypi.org/project/pvextractor/

from pvextractor.gui import PVSlicer
pv = PVSlicer('Desktop/M17_Q/JVO_data-cube/M17_13CO_22.1arcsec_vel0.1_sph_v1.0.fits')

I have an error with global name 'array'

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pvextractor/gui.py", line 235, in __init__
    self.shape = array.shape
NameError: global name 'array' is not defined

Not sure to understand what is missing

**Comment by keflavich** [comment]
@didelon Install spectral-cube, then it will work.   I'll also push a bugfix for this though.

**Comment by didelon** [comment]
I tried to install spectral cube...but I have a pb with casa-formats-io, and trying to install casa-formats-io directly doesn't work either

sorry for this silly requests

pip install spectral-cube
Collecting spectral-cube
  Downloading https://files.pythonhosted.org/packages/a7/f7/39fca18a6e0db9004787a32259c8eeb782168c3210baf209cc693551b75f/spectral-cube-0.6.2.tar.gz (260kB)
     |████████████████████████████████| 266kB 9.0MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: six in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from spectral-cube) (1.16.0)
Collecting dask[array] (from spectral-cube)
  Downloading https://files.pythonhosted.org/packages/58/80/6059587dcf80821fbccdc1f06b6d3fd29b64c9b38fbf1ea42889460de3de/dask-1.2.2-py2.py3-none-any.whl (717kB)
     |████████████████████████████████| 727kB 24.5MB/s 
Collecting radio-beam>=0.3.3 (from spectral-cube)
  Downloading https://files.pythonhosted.org/packages/cc/a4/60534f915d7329006967c826e7b4829a0bcef88803e66bdc69832f0b43db/radio-beam-0.3.4.tar.gz (92kB)
     |████████████████████████████████| 102kB 39.6MB/s 
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting joblib (from spectral-cube)
  Downloading https://files.pythonhosted.org/packages/28/5c/cf6a2b65a321c4a209efcdf64c2689efae2cb62661f8f6f4bb28547cf1bf/joblib-0.14.1-py2.py3-none-any.whl (294kB)
     |████████████████████████████████| 296kB 24.2MB/s 
Requirement already satisfied: astropy in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from spectral-cube) (2.0.16)
Requirement already satisfied: numpy>=1.8.0 in /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages (from spectral-cube) (1.16.6)
Collecting casa-formats-io (from spectral-cube)
  ERROR: Could not find a version that satisfies the requirement casa-formats-io (from spectral-cube) (from versions: none)
ERROR: No matching distribution found for casa-formats-io (from spectral-cube)

pip install casa-formats-io 
Collecting casa-formats-io
  ERROR: Could not find a version that satisfies the requirement casa-formats-io (from versions: none)
ERROR: No matching distribution found for casa-formats-io

**Comment by keflavich** [comment]
This is because you're using python2.7.  We can't support python2 any longer, as the language is [deprecated](https://www.python.org/doc/sunset-python-2/).  Please upgrade to a recent version (e.g., 3.10 or 3.11) and try again.

**Comment by didelon** [comment]
ok... but with python 3 (3.9.6 is not enough?) it fails also :-/

Python 3.9.6 (default, May  7 2023, 23:32:44) 
[Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> from pvextractor.gui import PVSlicer

 >>> pv = PVSlicer('/Users/didelon/Desktop/M17_Q/JVO_data-cube/M17_13CO_22.1arcsec_vel0.1_sph_v1.0.fits')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/didelon/Library/Python/3.9/lib/python/site-packages/pvextractor/gui.py", line 234, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/didelon/Library/Python/3.9/lib/python/site-packages/pvextractor/gui.py", line 242, in wrapper
    return func(self, *args, **kwargs)
  File "/Users/didelon/Library/Python/3.9/lib/python/site-packages/pvextractor/gui.py", line 254, in __init__
    if hasattr(filename_or_cube, 'filled_data') or issubclass(filename_or_cube, BaseSpectralCube):
TypeError: issubclass() arg 1 must be a class

**Comment by keflavich** [comment]
that looks like a real error.  I'll investigate.

**Comment by keflavich** [comment]
Ah, that error message again indicates you're on an old version of pvextractor.  This line:
https://github.com/radio-astro-tools/pvextractor/blob/9911f297a7978c8afb3fe6f6d937d6b03161031c/pvextractor/gui.py#L254
already contains the fix - `isinstance` instead of `issubclass`

**Comment by astrofrog** [comment]
This should be fixed in pvextractor v0.4 released today so I'll go ahead and close this - feel free to re-open if you are still having issues.
