### ISSUE TITLE
_astropy_init.py uses deprecated functions

### ISSUE THREAD

**Issue by jfoster17** [radio-astro-tools/pvextractor#119]
In _astropy_init.py, this package calls and uses

```
from astropy.config.configuration import (
        update_default_config,
        ConfigurationDefaultMissingError,
        ConfigurationDefaultMissingWarning)
```

But both `update_default_config` and `ConfigurationDefaultMissingWarning` are deprecated since astropy 5.0 and have been removed in the latest dev version of astropy, causing import errors for this package.

**Comment by keflavich** [comment]
@jfoster17 I don't suppose you know the easy immediate fix?  I think we need to migrate the underlying package infrastructure to the more modern astropy stuff, but I don't have that process readily to mind.

**Comment by jfoster17** [comment]
I'm afraid I don't know the best way to fix/update this. I'm not really up-to-date on astropy -- but I am pinging @astrofrog since this is causes our glue test suite to fail for the latest astropy dev versions.

**Comment by astrofrog** [comment]
Looking into it now!

**Comment by astrofrog** [comment]
Fixed in https://github.com/radio-astro-tools/pvextractor/pull/120 and pvextractor v0.4 released
