### ISSUE TITLE
Rename package to pvslicer?

### ISSUE THREAD

**Issue by astrofrog** [radio-astro-tools/pvextractor#24]
@keflavich @ChrisBeaumont @low-sky - what do you think about renaming this to `pvslicer`?

**Comment by astrofrog** [comment]
Thinking about this a bit more again - I think this package would actually be useful to other areas of science too, so I wonder if we could consider renaming to ``cubeslicer`` and making sure that the astronomy-related functionality has its own section in the docs? But that we also show how to use it with arbitrary Numpy arrays?

**Comment by keflavich** [comment]
Yes, that sounds like a reasonable thing to do.  It might be easier, though, to extract the core functionality and make that its own package (`cubeutils`) and have `pvextractor` inherit from that, just to avoid changing APIs on folks already using this toolkit, and also to maintain the radio-astro-tools branding for the pvextractor while moving the more general functionality elsewhere

**Comment by astrofrog** [comment]
Oh, I like that idea. I'd be happy to maintain ``cubeslicer`` if you maintain ``pvextractor``? Where should ``cubeslicer`` live? It might get more exposure to non-astro folk in the glue repo for example.

**Comment by keflavich** [comment]
Maybe let it be standalone?  I think the ginga folks would want to use it.  Glue is a good home, though.

**Comment by keflavich** [comment]
Looks like we lost the opportunity to do this.  `pvextractor` it is, even though it is more generally a cube slicer (and is used within glue, right?)
