### ISSUE TITLE
Not all WCS objects have pc attribute

### ISSUE THREAD

**Issue by ChrisBeaumont** [radio-astro-tools/pvextractor#55]
cc @astrofrog 

Some of my fits cubes don't have a pc attribute, which causes this function to crash

https://github.com/radio-astro-tools/pvextractor/blob/18dca9513819b2ef4bbb701dc685e0cf9052f778/pvextractor/utils/wcs_slicing.py#L38

Can we skip this line if `pc` doesn't exist?

**Comment by keflavich** [comment]
Looks like this was solved in https://github.com/radio-astro-tools/pvextractor/commit/0f9de274963aeadc52402407ddf3ea03c13665e2
