### ISSUE TITLE
Error on CALIFA cubes

### ISSUE THREAD

**Issue by ChrisBeaumont** [radio-astro-tools/pvextractor#58]
@stscieisenhamer first reported this on https://github.com/glue-viz/glue/issues/527

That error message is triggered in https://github.com/radio-astro-tools/pvextractor/blob/master/pvextractor/utils/wcs_utils.py#L70

My guess is that CTYPE3 has some unexpected label in CALIFA images

**Comment by keflavich** [comment]
This was a niche problem that may recur, but we need data to work with and a clearer path.  I'm closing for now.
