### ISSUE TITLE
GUI tests fail because pyqt4 is not available

### ISSUE THREAD

**Issue by keflavich** [radio-astro-tools/pvextractor#80]
cc @astrofrog

Failures show up in this PR:
https://github.com/radio-astro-tools/pvextractor/pull/79

PyQT4 can't be imported so GUI tests fail.  How do we install pyqt4?  It seems likely some change in package-template / helpers is behind this

**Comment by astrofrog** [comment]
The GUI test now works (PyQt5 is pip installable)
