### ISSUE TITLE
ImportError: The pvextractor GUI is not compatible with matplotlib >=2.

### ISSUE THREAD

**Issue by PeterSchilke** [radio-astro-tools/pvextractor#85]
The title says it all - we have matplotlib 2.0 or 2.1 installed on all machines.

**Comment by keflavich** [comment]
@astrofrog - any thoughts about this?

**Comment by tomr-stargazer** [comment]
I'm also interested in what happens in this space! (:

**Comment by astrofrog** [comment]
I'm going to try and fix this shortly.

**Comment by 3rico** [comment]
Did anyone fix this? :-( i still have this problem one year later...
