### ISSUE TITLE
Install issue

### ISSUE THREAD

**Issue by lhogarth** [radio-astro-tools/pvextractor#92]
Hi,

I'm trying to install pvextractor on my Ubuntu machine using Python 3.6, but I'm receiving an error when running the command:

pip install https://github.com/ericmandel/pyds9/archive/master.zip

The message where the install breaks is as follows:

```
/home/lhogarth/miniconda2/envs/py36/compiler_compat/ld: cannot find -lpthread
/home/lhogarth/miniconda2/envs/py36/compiler_compat/ld: cannot find -lc
collect2: error: ld returned 1 exit status
 error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/home/lhogarth/miniconda2/envs/py36/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-ktvvjcnn/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-lgk24e5k/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-ktvvjcnn/
```

I've tried reinstalling the packages it can't seem to find but I've had no joy so far. My guess is it might be something to do with the fact that many of my packages are with an Anaconda environment. There may be a way to link the paths to these directories, but I'm still quite new to using Ubuntu commands!

Thanks in advance and best wishes,

Lucy Hogarth

**Comment by keflavich** [comment]
cc @astrofrog do you recognize this error?  I don't have any ideas; I don't think we have compiled code in pvextractor

**Comment by astrofrog** [comment]
@lhogarth - since this was a little while back and unlikely to be related to pvextractor as @keflavich mentioned, I'm going to close this. If you continue to have issues, feel free to share the complete output from the pip command so we can take a closer look.
