### ISSUE TITLE
Time for a new release?

### ISSUE THREAD

**Issue by smaret** [radio-astro-tools/pvextractor#97]
The latest version of `pvextractor` was released on January 2018. This version is not compatible with Astropy > 4.0. For example, it tries to import the `six` module from `astropy.extern` and fails.

Perhaps it's time for a new release on PyPI?

**Comment by astrofrog** [comment]
pvextractor v0.2 is now released and is available on PyPI and conda-forge!

**Comment by smaret** [comment]
Thanks!
